"""questions update

Revision ID: 2d5f2776cf8d
Revises: 1128ad2500fa
Create Date: 2025-05-03 03:19:35.902471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5f2776cf8d'
down_revision: Union[str, None] = '1128ad2500fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('questions', sa.Column('explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'is_deleted')
    # ### end Alembic commands ###
